// Code generated by go-swagger; DO NOT EDIT.

// Package restapi OnceHuman工具集API
//
//	提供OnceHuman游戏相关的计算工具API
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /api/v1
//	Version: 1.0.0
//	License: MIT
//	Contact: API Support<support@oncehuman.tools>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
