// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "提供OnceHuman游戏相关的计算工具API",
    "title": "OnceHuman工具集API",
    "contact": {
      "name": "API Support",
      "email": "support@oncehuman.tools"
    },
    "license": {
      "name": "MIT"
    },
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/health": {
      "get": {
        "description": "检查服务是否正常运行",
        "tags": [
          "System"
        ],
        "summary": "健康检查",
        "operationId": "healthCheck",
        "responses": {
          "200": {
            "description": "服务正常",
            "schema": {
              "$ref": "#/definitions/HealthResponse"
            }
          }
        }
      }
    },
    "/mod/affix/list": {
      "get": {
        "description": "获取所有可用的模组词条",
        "tags": [
          "Mod"
        ],
        "summary": "获取词条列表",
        "operationId": "listAffixes",
        "responses": {
          "200": {
            "description": "成功获取词条列表",
            "schema": {
              "$ref": "#/definitions/AffixListResponse"
            }
          }
        }
      }
    },
    "/mod/affix/probability": {
      "post": {
        "description": "计算指定词条组合出现的概率",
        "tags": [
          "Mod"
        ],
        "summary": "计算模组词条概率",
        "operationId": "calculateAffixProbability",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AffixProbabilityRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "计算成功",
            "schema": {
              "$ref": "#/definitions/AffixProbabilityResponse"
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/mod/strengthen/probability": {
      "post": {
        "description": "计算模组词条强化到目标等级的概率",
        "tags": [
          "Mod"
        ],
        "summary": "计算强化成功概率",
        "operationId": "calculateStrengthenProbability",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/StrengthenProbabilityRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "计算成功",
            "schema": {
              "$ref": "#/definitions/StrengthenProbabilityResponse"
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/tools": {
      "get": {
        "description": "获取所有可用的工具",
        "tags": [
          "Tools"
        ],
        "summary": "获取工具列表",
        "operationId": "listTools",
        "responses": {
          "200": {
            "description": "成功获取工具列表",
            "schema": {
              "$ref": "#/definitions/ToolsListResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Affix": {
      "type": "object",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "category": {
          "type": "string",
          "example": "damage"
        },
        "description": {
          "type": "string",
          "example": "提升异常状态伤害"
        },
        "id": {
          "type": "integer",
          "format": "int32",
          "example": 1
        },
        "name": {
          "type": "string",
          "example": "异常伤害"
        }
      }
    },
    "AffixListResponse": {
      "type": "object",
      "required": [
        "affixes"
      ],
      "properties": {
        "affixes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Affix"
          }
        },
        "total": {
          "type": "integer",
          "format": "int32",
          "example": 10
        }
      }
    },
    "AffixProbabilityRequest": {
      "type": "object",
      "required": [
        "slotCount",
        "targetAffixIds"
      ],
      "properties": {
        "showCombinations": {
          "type": "boolean",
          "default": false
        },
        "slotCount": {
          "type": "integer",
          "format": "int32",
          "maximum": 10,
          "minimum": 1,
          "example": 3
        },
        "targetAffixIds": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "integer",
            "format": "int32"
          },
          "example": [
            1,
            4,
            5,
            6
          ]
        }
      }
    },
    "AffixProbabilityResponse": {
      "type": "object",
      "required": [
        "probability",
        "probabilityPercent",
        "totalCombinations",
        "validCombinations"
      ],
      "properties": {
        "combinations": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int32"
            }
          },
          "example": [
            [
              1,
              4,
              5
            ],
            [
              1,
              4,
              6
            ],
            [
              1,
              5,
              6
            ],
            [
              4,
              5,
              6
            ]
          ]
        },
        "probability": {
          "type": "number",
          "format": "double",
          "example": 0.0333
        },
        "probabilityPercent": {
          "type": "number",
          "format": "double",
          "example": 3.33
        },
        "slotCount": {
          "type": "integer",
          "format": "int32",
          "example": 3
        },
        "targetRange": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          },
          "example": [
            1,
            4,
            5,
            6
          ]
        },
        "totalCombinations": {
          "type": "integer",
          "format": "int64",
          "example": 120
        },
        "validCombinations": {
          "type": "integer",
          "format": "int64",
          "example": 4
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "details": {
          "type": "object"
        },
        "error": {
          "type": "string",
          "example": "bad_request"
        },
        "message": {
          "type": "string",
          "example": "Invalid request parameters"
        }
      }
    },
    "HealthResponse": {
      "type": "object",
      "required": [
        "status",
        "timestamp"
      ],
      "properties": {
        "status": {
          "type": "string",
          "example": "ok"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "version": {
          "type": "string",
          "example": "1.0.0"
        }
      }
    },
    "StrengthenPath": {
      "type": "object",
      "properties": {
        "finalLevels": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "steps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StrengthenStep"
          }
        },
        "success": {
          "type": "boolean"
        }
      }
    },
    "StrengthenProbabilityRequest": {
      "type": "object",
      "required": [
        "initialLevels",
        "targetLevels"
      ],
      "properties": {
        "initialLevels": {
          "type": "array",
          "maxItems": 4,
          "minItems": 4,
          "items": {
            "type": "integer",
            "format": "int32",
            "maximum": 5,
            "minimum": 1
          },
          "example": [
            1,
            2,
            3,
            1
          ]
        },
        "orderIndependent": {
          "description": "true表示顺序无关模式，false表示位置对应模式",
          "type": "boolean",
          "default": true
        },
        "showPaths": {
          "type": "boolean",
          "default": false
        },
        "targetLevels": {
          "type": "array",
          "maxItems": 4,
          "minItems": 4,
          "items": {
            "type": "integer",
            "format": "int32",
            "maximum": 5,
            "minimum": 1
          },
          "example": [
            3,
            4,
            5,
            2
          ]
        }
      }
    },
    "StrengthenProbabilityResponse": {
      "type": "object",
      "required": [
        "probability",
        "probabilityPercent",
        "successfulOutcomes",
        "totalOutcomes"
      ],
      "properties": {
        "paths": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StrengthenPath"
          }
        },
        "probability": {
          "type": "number",
          "format": "double",
          "example": 0.75
        },
        "probabilityPercent": {
          "type": "number",
          "format": "double",
          "example": 75
        },
        "successfulOutcomes": {
          "type": "integer",
          "format": "int64",
          "example": 768
        },
        "totalOutcomes": {
          "type": "integer",
          "format": "int64",
          "example": 1024
        }
      }
    },
    "StrengthenStep": {
      "type": "object",
      "properties": {
        "newLevel": {
          "type": "integer",
          "format": "int32"
        },
        "slot": {
          "type": "integer",
          "format": "int32"
        },
        "step": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "Tool": {
      "type": "object",
      "required": [
        "id",
        "name",
        "category"
      ],
      "properties": {
        "category": {
          "type": "string",
          "example": "mod"
        },
        "description": {
          "type": "string",
          "example": "计算特定词条组合出现的概率"
        },
        "icon": {
          "type": "string",
          "example": "dice"
        },
        "id": {
          "type": "string",
          "example": "affix-probability"
        },
        "name": {
          "type": "string",
          "example": "模组词条概率计算器"
        }
      }
    },
    "ToolsListResponse": {
      "type": "object",
      "required": [
        "tools"
      ],
      "properties": {
        "categories": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "mod",
            "weapon",
            "character"
          ]
        },
        "tools": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tool"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "提供OnceHuman游戏相关的计算工具API",
    "title": "OnceHuman工具集API",
    "contact": {
      "name": "API Support",
      "email": "support@oncehuman.tools"
    },
    "license": {
      "name": "MIT"
    },
    "version": "1.0.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/health": {
      "get": {
        "description": "检查服务是否正常运行",
        "tags": [
          "System"
        ],
        "summary": "健康检查",
        "operationId": "healthCheck",
        "responses": {
          "200": {
            "description": "服务正常",
            "schema": {
              "$ref": "#/definitions/HealthResponse"
            }
          }
        }
      }
    },
    "/mod/affix/list": {
      "get": {
        "description": "获取所有可用的模组词条",
        "tags": [
          "Mod"
        ],
        "summary": "获取词条列表",
        "operationId": "listAffixes",
        "responses": {
          "200": {
            "description": "成功获取词条列表",
            "schema": {
              "$ref": "#/definitions/AffixListResponse"
            }
          }
        }
      }
    },
    "/mod/affix/probability": {
      "post": {
        "description": "计算指定词条组合出现的概率",
        "tags": [
          "Mod"
        ],
        "summary": "计算模组词条概率",
        "operationId": "calculateAffixProbability",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/AffixProbabilityRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "计算成功",
            "schema": {
              "$ref": "#/definitions/AffixProbabilityResponse"
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/mod/strengthen/probability": {
      "post": {
        "description": "计算模组词条强化到目标等级的概率",
        "tags": [
          "Mod"
        ],
        "summary": "计算强化成功概率",
        "operationId": "calculateStrengthenProbability",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/StrengthenProbabilityRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "计算成功",
            "schema": {
              "$ref": "#/definitions/StrengthenProbabilityResponse"
            }
          },
          "400": {
            "description": "请求参数错误",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/tools": {
      "get": {
        "description": "获取所有可用的工具",
        "tags": [
          "Tools"
        ],
        "summary": "获取工具列表",
        "operationId": "listTools",
        "responses": {
          "200": {
            "description": "成功获取工具列表",
            "schema": {
              "$ref": "#/definitions/ToolsListResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Affix": {
      "type": "object",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "category": {
          "type": "string",
          "example": "damage"
        },
        "description": {
          "type": "string",
          "example": "提升异常状态伤害"
        },
        "id": {
          "type": "integer",
          "format": "int32",
          "example": 1
        },
        "name": {
          "type": "string",
          "example": "异常伤害"
        }
      }
    },
    "AffixListResponse": {
      "type": "object",
      "required": [
        "affixes"
      ],
      "properties": {
        "affixes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Affix"
          }
        },
        "total": {
          "type": "integer",
          "format": "int32",
          "example": 10
        }
      }
    },
    "AffixProbabilityRequest": {
      "type": "object",
      "required": [
        "slotCount",
        "targetAffixIds"
      ],
      "properties": {
        "showCombinations": {
          "type": "boolean",
          "default": false
        },
        "slotCount": {
          "type": "integer",
          "format": "int32",
          "maximum": 10,
          "minimum": 1,
          "example": 3
        },
        "targetAffixIds": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "integer",
            "format": "int32"
          },
          "example": [
            1,
            4,
            5,
            6
          ]
        }
      }
    },
    "AffixProbabilityResponse": {
      "type": "object",
      "required": [
        "probability",
        "probabilityPercent",
        "totalCombinations",
        "validCombinations"
      ],
      "properties": {
        "combinations": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int32"
            }
          },
          "example": [
            [
              1,
              4,
              5
            ],
            [
              1,
              4,
              6
            ],
            [
              1,
              5,
              6
            ],
            [
              4,
              5,
              6
            ]
          ]
        },
        "probability": {
          "type": "number",
          "format": "double",
          "example": 0.0333
        },
        "probabilityPercent": {
          "type": "number",
          "format": "double",
          "example": 3.33
        },
        "slotCount": {
          "type": "integer",
          "format": "int32",
          "example": 3
        },
        "targetRange": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          },
          "example": [
            1,
            4,
            5,
            6
          ]
        },
        "totalCombinations": {
          "type": "integer",
          "format": "int64",
          "example": 120
        },
        "validCombinations": {
          "type": "integer",
          "format": "int64",
          "example": 4
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "required": [
        "error",
        "message"
      ],
      "properties": {
        "details": {
          "type": "object"
        },
        "error": {
          "type": "string",
          "example": "bad_request"
        },
        "message": {
          "type": "string",
          "example": "Invalid request parameters"
        }
      }
    },
    "HealthResponse": {
      "type": "object",
      "required": [
        "status",
        "timestamp"
      ],
      "properties": {
        "status": {
          "type": "string",
          "example": "ok"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "version": {
          "type": "string",
          "example": "1.0.0"
        }
      }
    },
    "StrengthenPath": {
      "type": "object",
      "properties": {
        "finalLevels": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "steps": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StrengthenStep"
          }
        },
        "success": {
          "type": "boolean"
        }
      }
    },
    "StrengthenProbabilityRequest": {
      "type": "object",
      "required": [
        "initialLevels",
        "targetLevels"
      ],
      "properties": {
        "initialLevels": {
          "type": "array",
          "maxItems": 4,
          "minItems": 4,
          "items": {
            "type": "integer",
            "format": "int32",
            "maximum": 5,
            "minimum": 1
          },
          "example": [
            1,
            2,
            3,
            1
          ]
        },
        "orderIndependent": {
          "description": "true表示顺序无关模式，false表示位置对应模式",
          "type": "boolean",
          "default": true
        },
        "showPaths": {
          "type": "boolean",
          "default": false
        },
        "targetLevels": {
          "type": "array",
          "maxItems": 4,
          "minItems": 4,
          "items": {
            "type": "integer",
            "format": "int32",
            "maximum": 5,
            "minimum": 1
          },
          "example": [
            3,
            4,
            5,
            2
          ]
        }
      }
    },
    "StrengthenProbabilityResponse": {
      "type": "object",
      "required": [
        "probability",
        "probabilityPercent",
        "successfulOutcomes",
        "totalOutcomes"
      ],
      "properties": {
        "paths": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StrengthenPath"
          }
        },
        "probability": {
          "type": "number",
          "format": "double",
          "example": 0.75
        },
        "probabilityPercent": {
          "type": "number",
          "format": "double",
          "example": 75
        },
        "successfulOutcomes": {
          "type": "integer",
          "format": "int64",
          "example": 768
        },
        "totalOutcomes": {
          "type": "integer",
          "format": "int64",
          "example": 1024
        }
      }
    },
    "StrengthenStep": {
      "type": "object",
      "properties": {
        "newLevel": {
          "type": "integer",
          "format": "int32"
        },
        "slot": {
          "type": "integer",
          "format": "int32"
        },
        "step": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "Tool": {
      "type": "object",
      "required": [
        "id",
        "name",
        "category"
      ],
      "properties": {
        "category": {
          "type": "string",
          "example": "mod"
        },
        "description": {
          "type": "string",
          "example": "计算特定词条组合出现的概率"
        },
        "icon": {
          "type": "string",
          "example": "dice"
        },
        "id": {
          "type": "string",
          "example": "affix-probability"
        },
        "name": {
          "type": "string",
          "example": "模组词条概率计算器"
        }
      }
    },
    "ToolsListResponse": {
      "type": "object",
      "required": [
        "tools"
      ],
      "properties": {
        "categories": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "mod",
            "weapon",
            "character"
          ]
        },
        "tools": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Tool"
          }
        }
      }
    }
  }
}`))
}
