swagger: "2.0"
info:
  title: OnceHuman工具集API
  description: 提供OnceHuman游戏相关的计算工具API
  version: 1.0.0
  contact:
    name: API Support
    email: support@oncehuman.tools
  license:
    name: MIT
basePath: /api/v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /health:
    get:
      tags:
        - System
      summary: 健康检查
      description: 检查服务是否正常运行
      operationId: healthCheck
      responses:
        200:
          description: 服务正常
          schema:
            $ref: "#/definitions/HealthResponse"

  /mod/affix/probability:
    post:
      tags:
        - Mod
      summary: 计算模组词条概率
      description: 计算指定词条组合出现的概率
      operationId: calculateAffixProbability
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/AffixProbabilityRequest"
      responses:
        200:
          description: 计算成功
          schema:
            $ref: "#/definitions/AffixProbabilityResponse"
        400:
          description: 请求参数错误
          schema:
            $ref: "#/definitions/ErrorResponse"

  /mod/affix/list:
    get:
      tags:
        - Mod
      summary: 获取词条列表
      description: 获取所有可用的模组词条
      operationId: listAffixes
      responses:
        200:
          description: 成功获取词条列表
          schema:
            $ref: "#/definitions/AffixListResponse"

  /mod/strengthen/probability:
    post:
      tags:
        - Mod
      summary: 计算强化成功概率
      description: 计算模组词条强化到目标等级的概率
      operationId: calculateStrengthenProbability
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/StrengthenProbabilityRequest"
      responses:
        200:
          description: 计算成功
          schema:
            $ref: "#/definitions/StrengthenProbabilityResponse"
        400:
          description: 请求参数错误
          schema:
            $ref: "#/definitions/ErrorResponse"

  /tools:
    get:
      tags:
        - Tools
      summary: 获取工具列表
      description: 获取所有可用的工具
      operationId: listTools
      responses:
        200:
          description: 成功获取工具列表
          schema:
            $ref: "#/definitions/ToolsListResponse"

definitions:
  HealthResponse:
    type: object
    required:
      - status
      - timestamp
    properties:
      status:
        type: string
        example: "ok"
      timestamp:
        type: string
        format: date-time
      version:
        type: string
        example: "1.0.0"

  ErrorResponse:
    type: object
    required:
      - error
      - message
    properties:
      error:
        type: string
        example: "bad_request"
      message:
        type: string
        example: "Invalid request parameters"
      details:
        type: object

  Affix:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int32
        example: 1
      name:
        type: string
        example: "异常伤害"
      description:
        type: string
        example: "提升异常状态伤害"
      category:
        type: string
        example: "damage"

  AffixListResponse:
    type: object
    required:
      - affixes
    properties:
      affixes:
        type: array
        items:
          $ref: "#/definitions/Affix"
      total:
        type: integer
        format: int32
        example: 10

  AffixProbabilityRequest:
    type: object
    required:
      - slotCount
      - targetAffixIds
    properties:
      slotCount:
        type: integer
        format: int32
        minimum: 1
        maximum: 10
        example: 3
      targetAffixIds:
        type: array
        items:
          type: integer
          format: int32
        minItems: 1
        example: [1, 4, 5, 6]
      showCombinations:
        type: boolean
        default: false

  AffixProbabilityResponse:
    type: object
    required:
      - probability
      - probabilityPercent
      - totalCombinations
      - validCombinations
    properties:
      probability:
        type: number
        format: double
        example: 0.0333
      probabilityPercent:
        type: number
        format: double
        example: 3.33
      totalCombinations:
        type: integer
        format: int64
        example: 120
      validCombinations:
        type: integer
        format: int64
        example: 4
      slotCount:
        type: integer
        format: int32
        example: 3
      targetRange:
        type: array
        items:
          type: integer
          format: int32
        example: [1, 4, 5, 6]
      combinations:
        type: array
        items:
          type: array
          items:
            type: integer
            format: int32
        example: [[1, 4, 5], [1, 4, 6], [1, 5, 6], [4, 5, 6]]

  StrengthenProbabilityRequest:
    type: object
    required:
      - initialLevels
      - targetLevels
    properties:
      initialLevels:
        type: array
        items:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
        minItems: 4
        maxItems: 4
        example: [1, 2, 3, 1]
      targetLevels:
        type: array
        items:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
        minItems: 4
        maxItems: 4
        example: [3, 4, 5, 2]
      orderIndependent:
        type: boolean
        default: true
        description: true表示顺序无关模式，false表示位置对应模式
      showPaths:
        type: boolean
        default: false

  StrengthenProbabilityResponse:
    type: object
    required:
      - probability
      - probabilityPercent
      - successfulOutcomes
      - totalOutcomes
    properties:
      probability:
        type: number
        format: double
        example: 0.75
      probabilityPercent:
        type: number
        format: double
        example: 75.0
      successfulOutcomes:
        type: integer
        format: int64
        example: 768
      totalOutcomes:
        type: integer
        format: int64
        example: 1024
      paths:
        type: array
        items:
          $ref: "#/definitions/StrengthenPath"

  StrengthenPath:
    type: object
    properties:
      success:
        type: boolean
      finalLevels:
        type: array
        items:
          type: integer
          format: int32
      steps:
        type: array
        items:
          $ref: "#/definitions/StrengthenStep"

  StrengthenStep:
    type: object
    properties:
      step:
        type: integer
        format: int32
      slot:
        type: integer
        format: int32
      newLevel:
        type: integer
        format: int32

  Tool:
    type: object
    required:
      - id
      - name
      - category
    properties:
      id:
        type: string
        example: "affix-probability"
      name:
        type: string
        example: "模组词条概率计算器"
      description:
        type: string
        example: "计算特定词条组合出现的概率"
      category:
        type: string
        example: "mod"
      icon:
        type: string
        example: "dice"

  ToolsListResponse:
    type: object
    required:
      - tools
    properties:
      tools:
        type: array
        items:
          $ref: "#/definitions/Tool"
      categories:
        type: array
        items:
          type: string
        example: ["mod", "weapon", "character"]