// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/oncehuman/tools/models"
)

// ListAffixesOKCode is the HTTP code returned for type ListAffixesOK
const ListAffixesOKCode int = 200

/*
ListAffixesOK 成功获取词条列表

swagger:response listAffixesOK
*/
type ListAffixesOK struct {

	/*
	  In: Body
	*/
	Payload *models.AffixListResponse `json:"body,omitempty"`
}

// NewListAffixesOK creates ListAffixesOK with default headers values
func NewListAffixesOK() *ListAffixesOK {

	return &ListAffixesOK{}
}

// WithPayload adds the payload to the list affixes o k response
func (o *ListAffixesOK) WithPayload(payload *models.AffixListResponse) *ListAffixesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list affixes o k response
func (o *ListAffixesOK) SetPayload(payload *models.AffixListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAffixesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
