// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StrengthenStep strengthen step
//
// swagger:model StrengthenStep
type StrengthenStep struct {

	// new level
	NewLevel int32 `json:"newLevel,omitempty"`

	// slot
	Slot int32 `json:"slot,omitempty"`

	// step
	Step int32 `json:"step,omitempty"`
}

// Validate validates this strengthen step
func (m *StrengthenStep) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this strengthen step based on context it is used
func (m *StrengthenStep) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StrengthenStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StrengthenStep) UnmarshalBinary(b []byte) error {
	var res StrengthenStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
