// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ToolsListResponse tools list response
//
// swagger:model ToolsListResponse
type ToolsListResponse struct {

	// categories
	// Example: ["mod","weapon","character"]
	Categories []string `json:"categories"`

	// tools
	// Required: true
	Tools []*Tool `json:"tools"`
}

// Validate validates this tools list response
func (m *ToolsListResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTools(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ToolsListResponse) validateTools(formats strfmt.Registry) error {

	if err := validate.Required("tools", "body", m.Tools); err != nil {
		return err
	}

	for i := 0; i < len(m.Tools); i++ {
		if swag.IsZero(m.Tools[i]) { // not required
			continue
		}

		if m.Tools[i] != nil {
			if err := m.Tools[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tools" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tools" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this tools list response based on the context it is used
func (m *ToolsListResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTools(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ToolsListResponse) contextValidateTools(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Tools); i++ {

		if m.Tools[i] != nil {

			if swag.IsZero(m.Tools[i]) { // not required
				return nil
			}

			if err := m.Tools[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tools" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tools" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ToolsListResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ToolsListResponse) UnmarshalBinary(b []byte) error {
	var res ToolsListResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
