// Code generated by go-swagger; DO NOT EDIT.

package tools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/oncehuman/tools/models"
)

// ListToolsOKCode is the HTTP code returned for type ListToolsOK
const ListToolsOKCode int = 200

/*
ListToolsOK 成功获取工具列表

swagger:response listToolsOK
*/
type ListToolsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ToolsListResponse `json:"body,omitempty"`
}

// NewListToolsOK creates ListToolsOK with default headers values
func NewListToolsOK() *ListToolsOK {

	return &ListToolsOK{}
}

// WithPayload adds the payload to the list tools o k response
func (o *ListToolsOK) WithPayload(payload *models.ToolsListResponse) *ListToolsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list tools o k response
func (o *ListToolsOK) SetPayload(payload *models.ToolsListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListToolsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
