// Code generated by go-swagger; DO NOT EDIT.

package tools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListToolsHandlerFunc turns a function with the right signature into a list tools handler
type ListToolsHandlerFunc func(ListToolsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListToolsHandlerFunc) Handle(params ListToolsParams) middleware.Responder {
	return fn(params)
}

// ListToolsHandler interface for that can handle valid list tools params
type ListToolsHandler interface {
	Handle(ListToolsParams) middleware.Responder
}

// NewListTools creates a new http.Handler for the list tools operation
func NewListTools(ctx *middleware.Context, handler ListToolsHandler) *ListTools {
	return &ListTools{Context: ctx, Handler: handler}
}

/*
	ListTools swagger:route GET /tools Tools listTools

获取工具列表

获取所有可用的工具
*/
type ListTools struct {
	Context *middleware.Context
	Handler ListToolsHandler
}

func (o *ListTools) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListToolsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
